groups:
  - name: error_alerts
    rules:
      - alert: HighErrorRate500
        expr: increase(http_requests_total{status="500"}[1m]) > 0
        for: 10s
        labels:
          severity: critical
        annotations:
          summary: "HTTP 500 error detected"
          description: "At least one HTTP 500 error has been detected in the last minute."

      - alert: HighUnauthorizedAttempts
        expr: increase(http_requests_total{status="404"}[1m]) > 0
        for: 1m
        labels:
          severity: warning
        annotations:
          summary: "High number of unauthorized attempts"
          description: "More than 5 unauthorized attempts (HTTP 404) detected in the last minute."
